version: '3'
services:
  mongo-db:
    image: mongo
    ports:
      - 27017:27017
  client-app:
    build: ./gomoku-game-react
    environment:
      - REACT_APP_PROXY_HOST=http://server-app:8080
    volumes:
      - ./gomoku-game-react/src:/gomoku-game-react/src
      - ./gomoku-game-react/public:/gomoku-game-react/public
    ports:
      - 3000:3000
  server-app:
    build: ./gomoku-game-service
    environment:
      - dbURI=mongodb://mongo-db:27017
    volumes:
      - ./gomoku-game-service/src:/gomoku-game-service/src
    ports:
      - 8080:8080